name: 'Dropbox Uploader Action'
description: 'This action will handle the upload process of your project to Dropbox.'
author: 'git9527'
branding:
  icon: 'upload-cloud'
  color: 'black'
runs:
  using: 'node20'
  main: 'index.js'
inputs:
  DROPBOX_REFRESH_TOKEN:
    description: 'Value should be a secret that is set in your repository settings'
    required: true

  DROPBOX_APP_KEY:
    description: 'Value should be a secret that is set in your repository settings'
    required: true

  DROPBOX_APP_SECRET:
    description: 'Value should be a secret that is set in your repository settings'
    required: true

  GLOB: 
    description: 'Glob that you want to upload to Dropbox e.g dir1/dir2/**/*.md or **/*.txt'
    required: false
    default: "**/*"
  
  DROPBOX_DESTINATION_PATH_PREFIX:
    description: 'The destination path prefix to save to in Dropbox. This will prepend the individual globs. Default value is "/"'
    required: false
    default: "/"

  DEBUG:
    description: "Enable debugging."
    required: false

