name: Build

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install
        run: npm install
      - name: Build
        run: npm run build

  release:
    name: Release
    needs: [build]
    if: contains(github.ref, 'tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Release GitHub Actions
        uses: technote-space/release-github-actions@v6
        with:
          BRANCH_NAME: releases/${MAJOR}
          CLEAN_TARGETS: '.gitignore,.github,*.lock,*.json'
          COMMIT_MESSAGE: 'build: release ${{ steps.get_tag.outputs.version }} via ${{ github.sha }}'